version: '3'

services:

# App container
  app:
    container_name: app
    image: app:1.0    
    build:
      context: .
      dockerfile: Dockerfile
    ports:
        - "80:4000"
    volumes:
        - ./todolist-on-herbs:/app
    networks: 
      dev:
        ipv4_address: 171.28.5.10

# Network service
networks: 
  dev:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    ipam:
      driver: default
      config:
      - subnet: 171.28.0.0/16
